project_id = "mtbxzehkfoashlcborey"

[functions.create-user]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.get-shared-pattern]
verify_jwt = false

[functions.generate-share-token]
verify_jwt = false
